kind: pipeline
type: docker
name: default

clone:
  skip_verify: true

steps:
  - name: pack
    when:
      branch:
        - main
    image: docker:dind
    environment:
      IMAGE: collapsenav-dotnet-tool-doc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t $IMAGE .
  - name: push
    when:
      branch:
        - main
    image: docker:dind
    environment:
      IMAGE: collapsenav-dotnet-tool-doc
      DOCKERUSER:
        from_secret: dockeruser
      DOCKERPWD:
        from_secret: dockerpwd
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - export datetag=$(date +%Y-%m-%d-%H-%M)
      - export dockerorigin=docker.collapsenav.cn
      - docker login $dockerorigin -u $DOCKERUSER -p $DOCKERPWD
      - docker tag $IMAGE $dockerorigin/doc/$IMAGE
      - docker tag $IMAGE $dockerorigin/doc/$IMAGE:$datetag
      - docker push $dockerorigin/doc/$IMAGE
      - docker push $dockerorigin/doc/$IMAGE:$datetag
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
