module.exports = {
    other: [
        {
            type: 'autogenerated',
            dirName: '.',
        }
    ],
    knowledge: [
        {
            type: 'autogenerated',
            dirName: 'knowledge',
        }
    ],
    dotnet: [
        {
            type: 'autogenerated',
            dirName: 'dotnet',
        }
    ],
    docusaurus: [
        {
            type: 'autogenerated',
            dirName: 'docusaurus'
        }
    ]
};